### ISSUE TITLE
Easier access to changelogs

### ISSUE THREAD

**Issue by adelarsq** [rust-lang/rust-www#345]
I'm new in this language. I find a little hard to find the changelogs. This is a important part from documentation and would be nice put a link on the [documentation](https://www.rust-lang.org/documentation.html).

**Comment by brson** [comment]
Agreed that this information should be more accessible. A direct link to RELEASES.md is probably sufficient now, but other changelogs might be important as well.

**Comment by adelarsq** [comment]
@brson What do you think about a new item on the [**References**](https://www.rust-lang.org/documentation.html) pointing to a **changelogs.md** with links to the [Rust Blog](http://blog.rust-lang.org)? I can create a PR for this.

**Comment by brson** [comment]
If we're talking about linking to all the release announcements and creating a new page, then there's a lot of overlap with [this page on the forge](https://forge.rust-lang.org/releases.html).

Perhaps we could clean up that page and link it instead of creating a new page on the website. In general the forge needs to be linked into the website if anybody's ever going to discover it, and it's intended to be a staging area for website improvements.

**Comment by adelarsq** [comment]
I just did add a link for the **changelogs.md**, so isn't necessary to worry if the [forge page](https://forge.rust-lang.org/releases.html) or the [blog](http://blog.rust-lang.org/) are updated or not.
Closing and waiting the merge.
