### ISSUE TITLE
Incorrect deployment of ru-RU/community.html

### ISSUE THREAD

**Issue by mkpankov** [rust-lang/rust-www#520]
Build [passed](https://travis-ci.org/rust-lang/rust-www/builds/159838894), but it did something strange:

```
uploading "community.html" with {:content_type=>"text/html", :acl=>"public-read"}
...
uploading "ru-RU/community.md" with {:content_type=>"text/plain", :acl=>"public-read"}
```

`ru-RU/community.md` was indeed uploaded and is available. `ru-RU/community.html` is old version that says page is untranslated.

Not really sure what broke it. I didn't test it locally, but it doesn't seem we need to do anything unusual when modifying existing files, right?

/cc @steveklabnik

**Comment by steveklabnik** [comment]
Hmmmmmmm. /cc @alexcrichton @brson

**Comment by alexcrichton** [comment]
Ok, did some investigation. Although I thought I was baffled by jekyll, turns out community.md has a UTF-8 BOM marker at the beginning, which apparently jekyll doesn't like. After [removing that](https://github.com/rust-lang/rust-www/commit/e0dacb6bbdbf4def991679d731e590c7df535897) jekyll appears to like this file again!

Hopefully should be updated live soon.

**Comment by steveklabnik** [comment]
sheesh!
