### ISSUE TITLE
Clarify policy for translation maintenance

### ISSUE THREAD

**Issue by AndrewBrinker** [rust-lang/rust-www#661]
As the Rust website grows and changes, and as it adds more translations, I think it will become increasingly important to have a clear procedure and clear expectations for how those translations should be kept up to date and correct.

Right now (and correct me if I am wrong), I believe the procedure is roughly as follows (whether this is a defined procedure or just how it has been done so far):

1. A community member submits a pull request with a translation (partial or complete) of the Rust website contents.
2. Someone else who speaks the translation language reviews the PR, giving feedback, and then making a recommendation to the assigned reviewer.
3. The assigned reviewer merges the PR.
4. If changes are made to the English website, the contributor of the translation may be pinged to update what they'd written.

This isn't a bad policy, I think, but there are a few things which could use clarification:

- Is the original contributor of the translation expected to provide updates to said translation as some of quasi-official translation maintainer? If they want to pass this responsibility on, do they need to do so explicitly? (Essentially, who is responsible for making sure the translation stays up to date? How can we make sure there is always at least one person on hand who speaks the relevant language and can keep the translation current?)
- If a user is making changes to the English version of the site, do they need to ping the other translators and work to make all changes land simultaneously? (Essentially, how in-sync do we expect translations to be?)
- Should all content on the site be treated equally with respect to translation? (In particular, the FAQ is quite large, and subject to a higher degree of growth and change as questions and answers are added or updated. Does it make sense to have the same policy for this document as for others?)
- How should partial translations be handled? If someone is submitting a change to the site, and identical versions of the page exist in their as-yet-untranslated form under another language folder, should the contributor update those pages as well?)

These questions connect to #659 and #660. Any thoughts?

**Comment by gabibbo97** [comment]
As I have just contributed with #678, I will give you my two cents.

As of today we have a large amount of PRs with translations made by people like me that would like to contribute to the project by translating the site and the docs.
I do believe that translations should be always accepted in the first place in order to increase the growth of the language among potential future users and maintainers.
Given that currently the https://www.rust-lang.org/en-US/contribute-translations.html translation policy is completely empty I, as a contributor have tried to adhere to a _self created_ guideline on translation.
Basically a translation should be:

- **Serious** translating technical documents is an important role and a good translation can make the difference in catching the attention of a potential future user
-**Subject to the personal touch of the translator** some concepts cannot be simply be transpiled from a language to another, also, if the translator has a CEN or CS degree, he can translate the terms with the scientific ones used in its country

Every translation, how complete or not it may be is a valuable addition to the Rust project and we should accept them, then the maintenance process begins, ideally, every modification to the website should undergo a staging area in whom some appointed translators and members can adapt their translation or vote to retard the publication of the site or simply leave that page unpublished and to be adapted at a later date.
Maintainers should be notified by email or mentioned in specific PRs or anything that might require some special attention.

**Comment by 3442853561** [comment]
@AndrewBrinker That is a great idea. However, there is a huge difference between language and language. So, it should be encouraged to localize their own characteristics pages.
