### ISSUE TITLE
"Friends of Rust": only allow entries for companies/individuals when they share their Rust experiences

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/rust-www#979]
There is at least one company on https://www.rust-lang.org/en-US/friends.html where there is no evidence that the company or their developers have used Rust at all: no hint which crates they use, no questions asked in forums how to use Rust or a specific crate, no known contributions to Rust oder crates - basically only "we use Rust, i promise".

Such entries do neither serve the Rust commmunity, nor people considering to use Rust.

CC @steveklabnik

**Comment by bstrie** [comment]
At some point, when the Friends page has grown large and unwieldy and we can easily afford to reject people, we should probably start doing this. Given that we only have a little over a hundred names on there now, though, I think it's arguable whether we've yet come to that point.

**Comment by kud1ing** [comment]
If we consider the length of the list to be more important than telling then truth, i am happy to close this.

**Comment by bstrie** [comment]
I'm not sure what sort of accusation you're leveling here. It's quite a stretch that anyone would be lying about using Rust at their company just to be able to put a logo on the friends page. And even assuming that some company is lying about using Rust, that would also imply that they're willing to fabricate the evidence you've asked for. Anyone could simply lie and say "ah, yes, we're using Rocket". They could even fork the Rocket repo and then trivially claim that the remainder of their code is proprietary.

In an ideal world, yes, I too would like every company using Rust to open-source their codebase and publish a comprehensive whitepaper about their use of Rust. We should continue to encourage that. Someday we should begin raising the bar to mandate that for new additions on the friends page, which is why this issue deserves to remain open. But today, Rust is still firmly in "early-adopter" territory, and using Rust at all implies taking a business risk for which we're quite thankful.

**Comment by kud1ing** [comment]
> I'm not sure what sort of accusation you're leveling here. It's quite a stretch that anyone would be lying about using Rust at their company just to be able to put a logo on the friends page.

Easy here, i am not accusing anyone, i am not naming names. I am saying i have reasonable doubts that at least on company/individual is using Rust or having any Rust experience at all.

Even if you think the burden of proof is not on the one claiming they use Rust but on the world, what does this claim gain anyone but the advertised?

**Comment by simeg** [comment]
How do you imagine this being verified? Do you have to contribute to Rust to make the list, or is it enough to mention the crates you use? The latter is obviously easy to fake.

I too see the problem of free advertisement but I'm not sure how the verification would be solved. Using your common sense takes you a long way, and I think it applies to this as well. Also it's not just advertisement for them, it's also advertisement for Rust!

**Comment by kud1ing** [comment]
@simeg I think this is a 2 step process: 1) decide that you want achieve something 2) try to achive something

> Also it's not just advertisement for them, it's also advertisement for Rust!

In what sense? If we put more "ACME Ltd." on this pae, which have nothing to do with Rust on this page, it dillutes and takes the deserved interest from Rust and the companies that have valuable insight to offer.

**Comment by simeg** [comment]
No need for an attitude, I was just interested in how you were thinking. I still don't understand how you want to make sure companies _actually_ use Rust, and also where you draw the line from having "high quality experience reports".

**Comment by kud1ing** [comment]
No attitude intendend. That is probably subjective but different from "i used it, but i can offer zero insight".

**Comment by kud1ing** [comment]
Whatever.
